### ISSUE TITLE
Dark mode bugs

### ISSUE THREAD

**Issue by lerno** [onrirr/c3-web#12]
Switch on dark mode, some things look bad, such as the code example. I'm not sure what colours we should pick to make it look good though.

**Comment by synzahrh** [comment]
A good color palette could be around RGB(25,25,25) to RGB(55,55,55) theyre darker shades of Brown that matches the full black website background

**Comment by lerno** [comment]
I would accept a PR for that.

**Comment by joshring** [comment]
I'll be fixing this in https://github.com/c3lang/c3-web/pull/43

**Comment by joshring** [comment]
Can close this now I think.
