### ISSUE TITLE
Search bugs?

### ISSUE THREAD

**Issue by lerno** [onrirr/c3-web#17]
It seems like search is rather conservative. It rarely gives any matches, so what's needed to make it work?

**Comment by lerno** [comment]
I guess this is a question for @onrirr

**Comment by ulughann** [comment]
İnteresting, do you have any examples?

**Comment by lerno** [comment]
Oh wait, maybe it was just dead because my wifi was reconnecting. But I note that `$` and `@` are skipped when searching, so that `$append` will also match general append, but since the `$` is meaningful in C3, it's not ideal.
