### ISSUE TITLE
Wrong statement in docs for Expression blocks.

### ISSUE THREAD

**Issue by kcvinker** [onrirr/c3-web#71]
Hi, 
There is a wrong statement in the example code for expression blocks in this link -
https://c3-lang.org/language-fundamentals/statements/#expression-blocks

The function below prints World!
```
fn void test()
{
    int a = 0;
    {|
        if (a) return;
        io::printf("Hello ");
        return;
    |};
    io::printf("World!\n");
}
```
This code will print `Hello World!` on screen, not `World!`. So the statement above is wrong.

**Comment by lerno** [comment]
Thank you, I've updated it.
